spring:
  profiles:
    active: prod
    group:
      local-env:
        - local
      prod-env:
        - prod
  batch:
    jdbc:
      initialize-schema: always

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB